openapi: 3.0.3 # definr la version de swagger.

info:
  title: WS-AFIRME #" TITULO DE LA API"
  version: v1.0.0
  description: API for managing transactions.
  contact:
    name: AHORRA SEGUROS
    email: alejandro.magb@gmail.com
    url: https://github.com/aledelorbe

tags:
  - name: "Transactions"
    description: Endpoints related to transaction data management.

paths:
  /api/transactions/get-all-transactions:
    get:
      summary: Get all transactions
      tags:
        - Transactions
      description: Returns a list of all stored transactions.
      responses:
        "200":
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"

  /api/transactions/by-reference/{reference}:
    get:
      summary: Get transaction by reference
      tags:
        - Transactions
      description: Finds a transaction using its unique reference.
      parameters:
        - name: reference
          in: path
          required: true
          description: Transaction reference
          schema:
            type: string
      responses:
        "200":
          description: Transaction found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "404":
          description: Transaction not found

  /api/transactions/cancel-Transaction/{id}/{reference}/{status}:
    put:
      summary: Cancel a transaction
      tags:
        - Transactions
      description: Updates the status of a transaction with the given ID and reference.
      parameters:
        - name: id
          in: path
          required: true
          description: Transaction ID
          schema:
            type: integer
            format: int64
        - name: reference
          in: path
          required: true
          description: Transaction reference
          schema:
            type: string
        - name: status
          in: path
          required: true
          description: New status
          schema:
            type: string
      responses:
        "201":
          description: Transaction canceled successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"
        "404":
          description: Transaction not found

  /api/transactions/save:
    post:
      summary: Save a new transaction
      tags:
        - Transactions
      description: Creates a new transaction.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Transaction"
      responses:
        "201":
          description: Transaction created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Transaction"

components:
  schemas:

    Transaction:
      type: object
      properties:
        id:
          type: integer
          format: int64
        operation:
          type: string
        amount:
          type: number
          format: double
        client:
          type: string
        secret:
          type: string
        reference:
          type: string
        status:
          type: string

